### ISSUE TITLE
Make a logo for Paperly

### ISSUE THREAD

**Issue by IshankaDSenevirathne** [IshankaDSenevirathne/EduEra#10]

**Comment by BrianAnakPintar** [comment]
Hi. I would like to contribute, can you assign it for me?

**Comment by IshankaDSenevirathne** [comment]
Hi, Thank you for considering the issue. You can design a logo and make a PR but we cannot confirm that we will be using that logo for this project but the PR will be accepted so that you will get a contribution towards hacktoberfest.
