### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by ARKEOLOGIST** [IshankaDSenevirathne/EduEra#20]
Currently, the documentation is written in an extremely poor fashion and needs improvements. 

Some basic examples include how to set up an environment for development on your computer, how to test for errors, some basic explanation of the folder structure, etc.

**Comment by RizkyRajitha** [comment]
hi @ARKEOLOGIST ,

thanks for checking our repository , 
we will consider your points and update the readme

**Comment by negiankit97** [comment]
@RizkyRajitha i'd like to work on this issue.

**Comment by RizkyRajitha** [comment]
hi @negiankit97 

thanks for checking out paperly , 

please do continue on this issue , 

update the readme file to with the as following 

1. update name to `paperly`
2. add table of content 
3. add `paperly` logo `https://github.com/IshankaDSenevirathne/Paperly/blob/master/public/Logo.png` directory 
4. how to locally set up development environment and prerequisites (`nodejs`)

might add some badges as well if applicable . 
refer https://shields.io/
