### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by ARKEOLOGIST** [IshankaDSenevirathne/EduEra#21]
While this repo does have a list of active contributors and accepts contributions from the community, there are no specific guidelines for people on how to contribute. 

Some basic do's and dont's are always welcome, especially for first-time contributors.

**Comment by RizkyRajitha** [comment]
hi @ARKEOLOGIST ,

we will add CONTRIBUTING.md file ,  to ease new contributors to working on issues

thanks

**Comment by negiankit97** [comment]
I'd like to work on this issue.

**Comment by negiankit97** [comment]
> I'd like to work on this issue.

@RizkyRajitha ?

**Comment by RizkyRajitha** [comment]
> > I'd like to work on this issue.
> 
> @RizkyRajitha ?
Hi @negiankit97 ,
we love to assign  this issue to you but we haven't finalized the contributing guidelines yet . 
so this issue will need a little more time.
