### ISSUE TITLE
App failures

### ISSUE THREAD

**Issue by bineetNaidu** [IshankaDSenevirathne/EduEra#9]
When We select any subject to get info the app breaks.
You can try out [link](https://paperly.vercel.app/subjectmenu) by selecting any subject.
I Would Like to work on it and fix the issue, If You allow me to work on this projects then feel free to assign me to work  on this issue

ERR Msg: -> 
```js
Cannot read property 'map' of undefined
```

**Comment by RizkyRajitha** [comment]
hi @bineetNaidu ,

thanks for investigating this issue .

this bug will be fixed in near future by our team members .

**Comment by bineetNaidu** [comment]
> hi @bineetNaidu ,
> 
> thanks for investigating this issue .
> 
> this bug will be fixed in near future by our team members .

I Would like work on this issue , then free to assign me this task.
